//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 8/19/2015 6:21:12 PM
namespace Common.Api.ExigoOData.ResourceManager
{
    
    /// <summary>
    /// There are no comments for ResourcesContext in the schema.
    /// </summary>
    public partial class ResourcesContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ResourcesContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ResourcesContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "CodeFirstNamespace", "Common.Api.ExigoOData.ResourceManager");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Common.Api.ExigoOData.ResourceManager", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CodeFirstNamespace.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ResourceManagement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ResourceManager> ResourceManagement
        {
            get
            {
                if ((this._ResourceManagement == null))
                {
                    this._ResourceManagement = base.CreateQuery<ResourceManager>("ResourceManagement");
                }
                return this._ResourceManagement;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ResourceManager> _ResourceManagement;
        /// <summary>
        /// There are no comments for ResourceManagerCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ResourceManagerCategory> ResourceManagerCategories
        {
            get
            {
                if ((this._ResourceManagerCategories == null))
                {
                    this._ResourceManagerCategories = base.CreateQuery<ResourceManagerCategory>("ResourceManagerCategories");
                }
                return this._ResourceManagerCategories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ResourceManagerCategory> _ResourceManagerCategories;
        /// <summary>
        /// There are no comments for ResourceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ResourceType> ResourceTypes
        {
            get
            {
                if ((this._ResourceTypes == null))
                {
                    this._ResourceTypes = base.CreateQuery<ResourceType>("ResourceTypes");
                }
                return this._ResourceTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ResourceType> _ResourceTypes;
        /// <summary>
        /// There are no comments for ResourceManagement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToResourceManagement(ResourceManager resourceManager)
        {
            base.AddObject("ResourceManagement", resourceManager);
        }
        /// <summary>
        /// There are no comments for ResourceManagerCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToResourceManagerCategories(ResourceManagerCategory resourceManagerCategory)
        {
            base.AddObject("ResourceManagerCategories", resourceManagerCategory);
        }
        /// <summary>
        /// There are no comments for ResourceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToResourceTypes(ResourceType resourceType)
        {
            base.AddObject("ResourceTypes", resourceType);
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.ResourceManager in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ResourceID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ResourceID")]
    public partial class ResourceManager
    {
        /// <summary>
        /// Create a new ResourceManager object.
        /// </summary>
        /// <param name="resourceID">Initial value of ResourceID.</param>
        /// <param name="resourceCategoryID">Initial value of ResourceCategoryID.</param>
        /// <param name="resourceStatusID">Initial value of ResourceStatusID.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="resourceActionTypeID">Initial value of ResourceActionTypeID.</param>
        /// <param name="resourceTypeID">Initial value of ResourceTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ResourceManager CreateResourceManager(int resourceID, int resourceCategoryID, int resourceStatusID, global::System.DateTime createdDate, int resourceActionTypeID, int resourceTypeID)
        {
            ResourceManager resourceManager = new ResourceManager();
            resourceManager.ResourceID = resourceID;
            resourceManager.ResourceCategoryID = resourceCategoryID;
            resourceManager.ResourceStatusID = resourceStatusID;
            resourceManager.CreatedDate = createdDate;
            resourceManager.ResourceActionTypeID = resourceActionTypeID;
            resourceManager.ResourceTypeID = resourceTypeID;
            return resourceManager;
        }
        /// <summary>
        /// There are no comments for Property ResourceID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ResourceID
        {
            get
            {
                return this._ResourceID;
            }
            set
            {
                this.OnResourceIDChanging(value);
                this._ResourceID = value;
                this.OnResourceIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ResourceID;
        partial void OnResourceIDChanging(int value);
        partial void OnResourceIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property ResourceCategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ResourceCategoryID
        {
            get
            {
                return this._ResourceCategoryID;
            }
            set
            {
                this.OnResourceCategoryIDChanging(value);
                this._ResourceCategoryID = value;
                this.OnResourceCategoryIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ResourceCategoryID;
        partial void OnResourceCategoryIDChanging(int value);
        partial void OnResourceCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ResourceStatusID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ResourceStatusID
        {
            get
            {
                return this._ResourceStatusID;
            }
            set
            {
                this.OnResourceStatusIDChanging(value);
                this._ResourceStatusID = value;
                this.OnResourceStatusIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ResourceStatusID;
        partial void OnResourceStatusIDChanging(int value);
        partial void OnResourceStatusIDChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property ResourceActionTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ResourceActionTypeID
        {
            get
            {
                return this._ResourceActionTypeID;
            }
            set
            {
                this.OnResourceActionTypeIDChanging(value);
                this._ResourceActionTypeID = value;
                this.OnResourceActionTypeIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ResourceActionTypeID;
        partial void OnResourceActionTypeIDChanging(int value);
        partial void OnResourceActionTypeIDChanged();
        /// <summary>
        /// There are no comments for Property UploadedFilePath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UploadedFilePath
        {
            get
            {
                return this._UploadedFilePath;
            }
            set
            {
                this.OnUploadedFilePathChanging(value);
                this._UploadedFilePath = value;
                this.OnUploadedFilePathChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UploadedFilePath;
        partial void OnUploadedFilePathChanging(string value);
        partial void OnUploadedFilePathChanged();
        /// <summary>
        /// There are no comments for Property ResourceTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ResourceTypeID
        {
            get
            {
                return this._ResourceTypeID;
            }
            set
            {
                this.OnResourceTypeIDChanging(value);
                this._ResourceTypeID = value;
                this.OnResourceTypeIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ResourceTypeID;
        partial void OnResourceTypeIDChanging(int value);
        partial void OnResourceTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ResourceOrder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ResourceOrder
        {
            get
            {
                return this._ResourceOrder;
            }
            set
            {
                this.OnResourceOrderChanging(value);
                this._ResourceOrder = value;
                this.OnResourceOrderChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ResourceOrder;
        partial void OnResourceOrderChanging(global::System.Nullable<int> value);
        partial void OnResourceOrderChanged();
        /// <summary>
        /// There are no comments for Property UploadedThumbnailPath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UploadedThumbnailPath
        {
            get
            {
                return this._UploadedThumbnailPath;
            }
            set
            {
                this.OnUploadedThumbnailPathChanging(value);
                this._UploadedThumbnailPath = value;
                this.OnUploadedThumbnailPathChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UploadedThumbnailPath;
        partial void OnUploadedThumbnailPathChanging(string value);
        partial void OnUploadedThumbnailPathChanged();
        /// <summary>
        /// There are no comments for ResourceManagerCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ResourceManagerCategory ResourceManagerCategory
        {
            get
            {
                return this._ResourceManagerCategory;
            }
            set
            {
                this._ResourceManagerCategory = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ResourceManagerCategory _ResourceManagerCategory;
        /// <summary>
        /// There are no comments for ResourceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ResourceType ResourceType
        {
            get
            {
                return this._ResourceType;
            }
            set
            {
                this._ResourceType = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ResourceType _ResourceType;
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.ResourceManagerCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ResourceCategoryID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ResourceCategoryID")]
    public partial class ResourceManagerCategory
    {
        /// <summary>
        /// Create a new ResourceManagerCategory object.
        /// </summary>
        /// <param name="resourceCategoryID">Initial value of ResourceCategoryID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ResourceManagerCategory CreateResourceManagerCategory(int resourceCategoryID)
        {
            ResourceManagerCategory resourceManagerCategory = new ResourceManagerCategory();
            resourceManagerCategory.ResourceCategoryID = resourceCategoryID;
            return resourceManagerCategory;
        }
        /// <summary>
        /// There are no comments for Property ResourceCategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ResourceCategoryID
        {
            get
            {
                return this._ResourceCategoryID;
            }
            set
            {
                this.OnResourceCategoryIDChanging(value);
                this._ResourceCategoryID = value;
                this.OnResourceCategoryIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ResourceCategoryID;
        partial void OnResourceCategoryIDChanging(int value);
        partial void OnResourceCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ResourceCategoryDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ResourceCategoryDescription
        {
            get
            {
                return this._ResourceCategoryDescription;
            }
            set
            {
                this.OnResourceCategoryDescriptionChanging(value);
                this._ResourceCategoryDescription = value;
                this.OnResourceCategoryDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ResourceCategoryDescription;
        partial void OnResourceCategoryDescriptionChanging(string value);
        partial void OnResourceCategoryDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ResourceCategoryOrder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ResourceCategoryOrder
        {
            get
            {
                return this._ResourceCategoryOrder;
            }
            set
            {
                this.OnResourceCategoryOrderChanging(value);
                this._ResourceCategoryOrder = value;
                this.OnResourceCategoryOrderChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ResourceCategoryOrder;
        partial void OnResourceCategoryOrderChanging(global::System.Nullable<int> value);
        partial void OnResourceCategoryOrderChanged();
        /// <summary>
        /// There are no comments for ResourceManagement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<ResourceManager> ResourceManagement
        {
            get
            {
                return this._ResourceManagement;
            }
            set
            {
                if ((value != null))
                {
                    this._ResourceManagement = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<ResourceManager> _ResourceManagement = new global::System.Collections.ObjectModel.Collection<ResourceManager>();
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.ResourceType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ResourceTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ResourceTypeID")]
    public partial class ResourceType
    {
        /// <summary>
        /// Create a new ResourceType object.
        /// </summary>
        /// <param name="resourceTypeID">Initial value of ResourceTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ResourceType CreateResourceType(int resourceTypeID)
        {
            ResourceType resourceType = new ResourceType();
            resourceType.ResourceTypeID = resourceTypeID;
            return resourceType;
        }
        /// <summary>
        /// There are no comments for Property ResourceTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ResourceTypeID
        {
            get
            {
                return this._ResourceTypeID;
            }
            set
            {
                this.OnResourceTypeIDChanging(value);
                this._ResourceTypeID = value;
                this.OnResourceTypeIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ResourceTypeID;
        partial void OnResourceTypeIDChanging(int value);
        partial void OnResourceTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ResourceTypeDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ResourceTypeDescription
        {
            get
            {
                return this._ResourceTypeDescription;
            }
            set
            {
                this.OnResourceTypeDescriptionChanging(value);
                this._ResourceTypeDescription = value;
                this.OnResourceTypeDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ResourceTypeDescription;
        partial void OnResourceTypeDescriptionChanging(string value);
        partial void OnResourceTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for ResourceManagement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<ResourceManager> ResourceManagement
        {
            get
            {
                return this._ResourceManagement;
            }
            set
            {
                if ((value != null))
                {
                    this._ResourceManagement = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<ResourceManager> _ResourceManagement = new global::System.Collections.ObjectModel.Collection<ResourceManager>();
    }
}
