//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/25/2015 1:06:04 PM
namespace Common.Api.ExigoOData.Calendars
{
    
    /// <summary>
    /// There are no comments for CalendarContext in the schema.
    /// </summary>
    public partial class CalendarContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CalendarContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CalendarContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "CodeFirstNamespace", "Common.Api.ExigoOData.Calendars");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Common.Api.ExigoOData.Calendars", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CodeFirstNamespace.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Calendars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Calendar> Calendars
        {
            get
            {
                if ((this._Calendars == null))
                {
                    this._Calendars = base.CreateQuery<Calendar>("Calendars");
                }
                return this._Calendars;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Calendar> _Calendars;
        /// <summary>
        /// There are no comments for ExigoCustomers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Customer> ExigoCustomers
        {
            get
            {
                if ((this._ExigoCustomers == null))
                {
                    this._ExigoCustomers = base.CreateQuery<Customer>("ExigoCustomers");
                }
                return this._ExigoCustomers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _ExigoCustomers;
        /// <summary>
        /// There are no comments for CalendarTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CalendarType> CalendarTypes
        {
            get
            {
                if ((this._CalendarTypes == null))
                {
                    this._CalendarTypes = base.CreateQuery<CalendarType>("CalendarTypes");
                }
                return this._CalendarTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CalendarType> _CalendarTypes;
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CalendarEvent> CalendarEvents
        {
            get
            {
                if ((this._CalendarEvents == null))
                {
                    this._CalendarEvents = base.CreateQuery<CalendarEvent>("CalendarEvents");
                }
                return this._CalendarEvents;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CalendarEvent> _CalendarEvents;
        /// <summary>
        /// There are no comments for CalendarEventPrivacyTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CalendarEventPrivacyType> CalendarEventPrivacyTypes
        {
            get
            {
                if ((this._CalendarEventPrivacyTypes == null))
                {
                    this._CalendarEventPrivacyTypes = base.CreateQuery<CalendarEventPrivacyType>("CalendarEventPrivacyTypes");
                }
                return this._CalendarEventPrivacyTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CalendarEventPrivacyType> _CalendarEventPrivacyTypes;
        /// <summary>
        /// There are no comments for CalendarEventStatuses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CalendarEventStatus> CalendarEventStatuses
        {
            get
            {
                if ((this._CalendarEventStatuses == null))
                {
                    this._CalendarEventStatuses = base.CreateQuery<CalendarEventStatus>("CalendarEventStatuses");
                }
                return this._CalendarEventStatuses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CalendarEventStatus> _CalendarEventStatuses;
        /// <summary>
        /// There are no comments for CalendarEventTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CalendarEventType> CalendarEventTypes
        {
            get
            {
                if ((this._CalendarEventTypes == null))
                {
                    this._CalendarEventTypes = base.CreateQuery<CalendarEventType>("CalendarEventTypes");
                }
                return this._CalendarEventTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CalendarEventType> _CalendarEventTypes;
        /// <summary>
        /// There are no comments for MonthlyCalendarEventRecurrenceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MonthlyCalendarEventRecurrenceType> MonthlyCalendarEventRecurrenceTypes
        {
            get
            {
                if ((this._MonthlyCalendarEventRecurrenceTypes == null))
                {
                    this._MonthlyCalendarEventRecurrenceTypes = base.CreateQuery<MonthlyCalendarEventRecurrenceType>("MonthlyCalendarEventRecurrenceTypes");
                }
                return this._MonthlyCalendarEventRecurrenceTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MonthlyCalendarEventRecurrenceType> _MonthlyCalendarEventRecurrenceTypes;
        /// <summary>
        /// There are no comments for CalendarEventRecurrenceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CalendarEventRecurrenceType> CalendarEventRecurrenceTypes
        {
            get
            {
                if ((this._CalendarEventRecurrenceTypes == null))
                {
                    this._CalendarEventRecurrenceTypes = base.CreateQuery<CalendarEventRecurrenceType>("CalendarEventRecurrenceTypes");
                }
                return this._CalendarEventRecurrenceTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CalendarEventRecurrenceType> _CalendarEventRecurrenceTypes;
        /// <summary>
        /// There are no comments for CalendarSubscriptions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CalendarSubscription> CalendarSubscriptions
        {
            get
            {
                if ((this._CalendarSubscriptions == null))
                {
                    this._CalendarSubscriptions = base.CreateQuery<CalendarSubscription>("CalendarSubscriptions");
                }
                return this._CalendarSubscriptions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CalendarSubscription> _CalendarSubscriptions;
        /// <summary>
        /// There are no comments for Calendars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendars(Calendar calendar)
        {
            base.AddObject("Calendars", calendar);
        }
        /// <summary>
        /// There are no comments for ExigoCustomers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToExigoCustomers(Customer customer)
        {
            base.AddObject("ExigoCustomers", customer);
        }
        /// <summary>
        /// There are no comments for CalendarTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendarTypes(CalendarType calendarType)
        {
            base.AddObject("CalendarTypes", calendarType);
        }
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendarEvents(CalendarEvent calendarEvent)
        {
            base.AddObject("CalendarEvents", calendarEvent);
        }
        /// <summary>
        /// There are no comments for CalendarEventPrivacyTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendarEventPrivacyTypes(CalendarEventPrivacyType calendarEventPrivacyType)
        {
            base.AddObject("CalendarEventPrivacyTypes", calendarEventPrivacyType);
        }
        /// <summary>
        /// There are no comments for CalendarEventStatuses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendarEventStatuses(CalendarEventStatus calendarEventStatus)
        {
            base.AddObject("CalendarEventStatuses", calendarEventStatus);
        }
        /// <summary>
        /// There are no comments for CalendarEventTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendarEventTypes(CalendarEventType calendarEventType)
        {
            base.AddObject("CalendarEventTypes", calendarEventType);
        }
        /// <summary>
        /// There are no comments for MonthlyCalendarEventRecurrenceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMonthlyCalendarEventRecurrenceTypes(MonthlyCalendarEventRecurrenceType monthlyCalendarEventRecurrenceType)
        {
            base.AddObject("MonthlyCalendarEventRecurrenceTypes", monthlyCalendarEventRecurrenceType);
        }
        /// <summary>
        /// There are no comments for CalendarEventRecurrenceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendarEventRecurrenceTypes(CalendarEventRecurrenceType calendarEventRecurrenceType)
        {
            base.AddObject("CalendarEventRecurrenceTypes", calendarEventRecurrenceType);
        }
        /// <summary>
        /// There are no comments for CalendarSubscriptions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCalendarSubscriptions(CalendarSubscription calendarSubscription)
        {
            base.AddObject("CalendarSubscriptions", calendarSubscription);
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.Calendar in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CalendarID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Calendars")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CalendarID")]
    public partial class Calendar : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Calendar object.
        /// </summary>
        /// <param name="calendarID">Initial value of CalendarID.</param>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="calendarTypeID">Initial value of CalendarTypeID.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Calendar CreateCalendar(global::System.Guid calendarID, int customerID, int calendarTypeID, global::System.DateTime createdDate)
        {
            Calendar calendar = new Calendar();
            calendar.CalendarID = calendarID;
            calendar.CustomerID = customerID;
            calendar.CalendarTypeID = calendarTypeID;
            calendar.CreatedDate = createdDate;
            return calendar;
        }
        /// <summary>
        /// There are no comments for Property CalendarID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid CalendarID
        {
            get
            {
                return this._CalendarID;
            }
            set
            {
                this.OnCalendarIDChanging(value);
                this._CalendarID = value;
                this.OnCalendarIDChanged();
                this.OnPropertyChanged("CalendarID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _CalendarID;
        partial void OnCalendarIDChanging(global::System.Guid value);
        partial void OnCalendarIDChanged();
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
                this.OnPropertyChanged("CustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CalendarTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarTypeID
        {
            get
            {
                return this._CalendarTypeID;
            }
            set
            {
                this.OnCalendarTypeIDChanging(value);
                this._CalendarTypeID = value;
                this.OnCalendarTypeIDChanged();
                this.OnPropertyChanged("CalendarTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarTypeID;
        partial void OnCalendarTypeIDChanging(int value);
        partial void OnCalendarTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this._Customer = value;
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
        /// <summary>
        /// There are no comments for CalendarType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CalendarType CalendarType
        {
            get
            {
                return this._CalendarType;
            }
            set
            {
                this._CalendarType = value;
                this.OnPropertyChanged("CalendarType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CalendarType _CalendarType;
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> CalendarEvents
        {
            get
            {
                return this._CalendarEvents;
            }
            set
            {
                this._CalendarEvents = value;
                this.OnPropertyChanged("CalendarEvents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> _CalendarEvents = new global::System.Data.Services.Client.DataServiceCollection<CalendarEvent>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for CalendarSubscriptions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CalendarSubscription> CalendarSubscriptions
        {
            get
            {
                return this._CalendarSubscriptions;
            }
            set
            {
                this._CalendarSubscriptions = value;
                this.OnPropertyChanged("CalendarSubscriptions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CalendarSubscription> _CalendarSubscriptions = new global::System.Data.Services.Client.DataServiceCollection<CalendarSubscription>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ExigoCustomers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerID")]
    public partial class Customer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Customer CreateCustomer(int customerID)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
                this.OnPropertyChanged("CustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this.OnCompanyChanging(value);
                this._Company = value;
                this.OnCompanyChanged();
                this.OnPropertyChanged("Company");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Company;
        partial void OnCompanyChanging(string value);
        partial void OnCompanyChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.CalendarType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CalendarTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CalendarTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CalendarTypeID")]
    public partial class CalendarType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CalendarType object.
        /// </summary>
        /// <param name="calendarTypeID">Initial value of CalendarTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CalendarType CreateCalendarType(int calendarTypeID)
        {
            CalendarType calendarType = new CalendarType();
            calendarType.CalendarTypeID = calendarTypeID;
            return calendarType;
        }
        /// <summary>
        /// There are no comments for Property CalendarTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarTypeID
        {
            get
            {
                return this._CalendarTypeID;
            }
            set
            {
                this.OnCalendarTypeIDChanging(value);
                this._CalendarTypeID = value;
                this.OnCalendarTypeIDChanged();
                this.OnPropertyChanged("CalendarTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarTypeID;
        partial void OnCalendarTypeIDChanging(int value);
        partial void OnCalendarTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarTypeDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CalendarTypeDescription
        {
            get
            {
                return this._CalendarTypeDescription;
            }
            set
            {
                this.OnCalendarTypeDescriptionChanging(value);
                this._CalendarTypeDescription = value;
                this.OnCalendarTypeDescriptionChanged();
                this.OnPropertyChanged("CalendarTypeDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CalendarTypeDescription;
        partial void OnCalendarTypeDescriptionChanging(string value);
        partial void OnCalendarTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for Calendars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Calendar> Calendars
        {
            get
            {
                return this._Calendars;
            }
            set
            {
                this._Calendars = value;
                this.OnPropertyChanged("Calendars");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Calendar> _Calendars = new global::System.Data.Services.Client.DataServiceCollection<Calendar>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.CalendarEvent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CalendarEventID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CalendarEvents")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CalendarEventID")]
    public partial class CalendarEvent : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CalendarEvent object.
        /// </summary>
        /// <param name="calendarEventID">Initial value of CalendarEventID.</param>
        /// <param name="calendarID">Initial value of CalendarID.</param>
        /// <param name="calendarEventTypeID">Initial value of CalendarEventTypeID.</param>
        /// <param name="calendarEventStatusID">Initial value of CalendarEventStatusID.</param>
        /// <param name="calendarEventPrivacyTypeID">Initial value of CalendarEventPrivacyTypeID.</param>
        /// <param name="createdByCustomerID">Initial value of CreatedByCustomerID.</param>
        /// <param name="isPrivateCopy">Initial value of IsPrivateCopy.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="endDate">Initial value of EndDate.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CalendarEvent CreateCalendarEvent(global::System.Guid calendarEventID, global::System.Guid calendarID, int calendarEventTypeID, int calendarEventStatusID, int calendarEventPrivacyTypeID, int createdByCustomerID, bool isPrivateCopy, global::System.DateTime startDate, global::System.DateTime endDate, global::System.DateTime createdDate)
        {
            CalendarEvent calendarEvent = new CalendarEvent();
            calendarEvent.CalendarEventID = calendarEventID;
            calendarEvent.CalendarID = calendarID;
            calendarEvent.CalendarEventTypeID = calendarEventTypeID;
            calendarEvent.CalendarEventStatusID = calendarEventStatusID;
            calendarEvent.CalendarEventPrivacyTypeID = calendarEventPrivacyTypeID;
            calendarEvent.CreatedByCustomerID = createdByCustomerID;
            calendarEvent.IsPrivateCopy = isPrivateCopy;
            calendarEvent.StartDate = startDate;
            calendarEvent.EndDate = endDate;
            calendarEvent.CreatedDate = createdDate;
            return calendarEvent;
        }
        /// <summary>
        /// There are no comments for Property CalendarEventID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid CalendarEventID
        {
            get
            {
                return this._CalendarEventID;
            }
            set
            {
                this.OnCalendarEventIDChanging(value);
                this._CalendarEventID = value;
                this.OnCalendarEventIDChanged();
                this.OnPropertyChanged("CalendarEventID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _CalendarEventID;
        partial void OnCalendarEventIDChanging(global::System.Guid value);
        partial void OnCalendarEventIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid CalendarID
        {
            get
            {
                return this._CalendarID;
            }
            set
            {
                this.OnCalendarIDChanging(value);
                this._CalendarID = value;
                this.OnCalendarIDChanged();
                this.OnPropertyChanged("CalendarID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _CalendarID;
        partial void OnCalendarIDChanging(global::System.Guid value);
        partial void OnCalendarIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarEventTypeID
        {
            get
            {
                return this._CalendarEventTypeID;
            }
            set
            {
                this.OnCalendarEventTypeIDChanging(value);
                this._CalendarEventTypeID = value;
                this.OnCalendarEventTypeIDChanged();
                this.OnPropertyChanged("CalendarEventTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarEventTypeID;
        partial void OnCalendarEventTypeIDChanging(int value);
        partial void OnCalendarEventTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventStatusID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarEventStatusID
        {
            get
            {
                return this._CalendarEventStatusID;
            }
            set
            {
                this.OnCalendarEventStatusIDChanging(value);
                this._CalendarEventStatusID = value;
                this.OnCalendarEventStatusIDChanged();
                this.OnPropertyChanged("CalendarEventStatusID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarEventStatusID;
        partial void OnCalendarEventStatusIDChanging(int value);
        partial void OnCalendarEventStatusIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventPrivacyTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarEventPrivacyTypeID
        {
            get
            {
                return this._CalendarEventPrivacyTypeID;
            }
            set
            {
                this.OnCalendarEventPrivacyTypeIDChanging(value);
                this._CalendarEventPrivacyTypeID = value;
                this.OnCalendarEventPrivacyTypeIDChanged();
                this.OnPropertyChanged("CalendarEventPrivacyTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarEventPrivacyTypeID;
        partial void OnCalendarEventPrivacyTypeIDChanging(int value);
        partial void OnCalendarEventPrivacyTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CreatedByCustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CreatedByCustomerID
        {
            get
            {
                return this._CreatedByCustomerID;
            }
            set
            {
                this.OnCreatedByCustomerIDChanging(value);
                this._CreatedByCustomerID = value;
                this.OnCreatedByCustomerIDChanged();
                this.OnPropertyChanged("CreatedByCustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CreatedByCustomerID;
        partial void OnCreatedByCustomerIDChanging(int value);
        partial void OnCreatedByCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property IsPrivateCopy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsPrivateCopy
        {
            get
            {
                return this._IsPrivateCopy;
            }
            set
            {
                this.OnIsPrivateCopyChanging(value);
                this._IsPrivateCopy = value;
                this.OnIsPrivateCopyChanged();
                this.OnPropertyChanged("IsPrivateCopy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsPrivateCopy;
        partial void OnIsPrivateCopyChanging(bool value);
        partial void OnIsPrivateCopyChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Summary in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Summary
        {
            get
            {
                return this._Summary;
            }
            set
            {
                this.OnSummaryChanging(value);
                this._Summary = value;
                this.OnSummaryChanged();
                this.OnPropertyChanged("Summary");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Summary;
        partial void OnSummaryChanging(string value);
        partial void OnSummaryChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this._StartDate = value;
                this.OnStartDateChanged();
                this.OnPropertyChanged("StartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this._EndDate = value;
                this.OnEndDateChanged();
                this.OnPropertyChanged("EndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property Field1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field1
        {
            get
            {
                return this._Field1;
            }
            set
            {
                this.OnField1Changing(value);
                this._Field1 = value;
                this.OnField1Changed();
                this.OnPropertyChanged("Field1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field1;
        partial void OnField1Changing(string value);
        partial void OnField1Changed();
        /// <summary>
        /// There are no comments for Property Field2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field2
        {
            get
            {
                return this._Field2;
            }
            set
            {
                this.OnField2Changing(value);
                this._Field2 = value;
                this.OnField2Changed();
                this.OnPropertyChanged("Field2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field2;
        partial void OnField2Changing(string value);
        partial void OnField2Changed();
        /// <summary>
        /// There are no comments for Property Field3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field3
        {
            get
            {
                return this._Field3;
            }
            set
            {
                this.OnField3Changing(value);
                this._Field3 = value;
                this.OnField3Changed();
                this.OnPropertyChanged("Field3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field3;
        partial void OnField3Changing(string value);
        partial void OnField3Changed();
        /// <summary>
        /// There are no comments for Property Field4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field4
        {
            get
            {
                return this._Field4;
            }
            set
            {
                this.OnField4Changing(value);
                this._Field4 = value;
                this.OnField4Changed();
                this.OnPropertyChanged("Field4");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field4;
        partial void OnField4Changing(string value);
        partial void OnField4Changed();
        /// <summary>
        /// There are no comments for Property Field5 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field5
        {
            get
            {
                return this._Field5;
            }
            set
            {
                this.OnField5Changing(value);
                this._Field5 = value;
                this.OnField5Changed();
                this.OnPropertyChanged("Field5");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field5;
        partial void OnField5Changing(string value);
        partial void OnField5Changed();
        /// <summary>
        /// There are no comments for Property Field6 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field6
        {
            get
            {
                return this._Field6;
            }
            set
            {
                this.OnField6Changing(value);
                this._Field6 = value;
                this.OnField6Changed();
                this.OnPropertyChanged("Field6");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field6;
        partial void OnField6Changing(string value);
        partial void OnField6Changed();
        /// <summary>
        /// There are no comments for Property Field7 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field7
        {
            get
            {
                return this._Field7;
            }
            set
            {
                this.OnField7Changing(value);
                this._Field7 = value;
                this.OnField7Changed();
                this.OnPropertyChanged("Field7");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field7;
        partial void OnField7Changing(string value);
        partial void OnField7Changed();
        /// <summary>
        /// There are no comments for Property Field8 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field8
        {
            get
            {
                return this._Field8;
            }
            set
            {
                this.OnField8Changing(value);
                this._Field8 = value;
                this.OnField8Changed();
                this.OnPropertyChanged("Field8");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field8;
        partial void OnField8Changing(string value);
        partial void OnField8Changed();
        /// <summary>
        /// There are no comments for Property Field9 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field9
        {
            get
            {
                return this._Field9;
            }
            set
            {
                this.OnField9Changing(value);
                this._Field9 = value;
                this.OnField9Changed();
                this.OnPropertyChanged("Field9");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field9;
        partial void OnField9Changing(string value);
        partial void OnField9Changed();
        /// <summary>
        /// There are no comments for Property Field10 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Field10
        {
            get
            {
                return this._Field10;
            }
            set
            {
                this.OnField10Changing(value);
                this._Field10 = value;
                this.OnField10Changed();
                this.OnPropertyChanged("Field10");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Field10;
        partial void OnField10Changing(string value);
        partial void OnField10Changed();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventRecurrenceTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> CalendarEventRecurrenceTypeID
        {
            get
            {
                return this._CalendarEventRecurrenceTypeID;
            }
            set
            {
                this.OnCalendarEventRecurrenceTypeIDChanging(value);
                this._CalendarEventRecurrenceTypeID = value;
                this.OnCalendarEventRecurrenceTypeIDChanged();
                this.OnPropertyChanged("CalendarEventRecurrenceTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _CalendarEventRecurrenceTypeID;
        partial void OnCalendarEventRecurrenceTypeIDChanging(global::System.Nullable<int> value);
        partial void OnCalendarEventRecurrenceTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventRecurrenceInterval in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> CalendarEventRecurrenceInterval
        {
            get
            {
                return this._CalendarEventRecurrenceInterval;
            }
            set
            {
                this.OnCalendarEventRecurrenceIntervalChanging(value);
                this._CalendarEventRecurrenceInterval = value;
                this.OnCalendarEventRecurrenceIntervalChanged();
                this.OnPropertyChanged("CalendarEventRecurrenceInterval");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _CalendarEventRecurrenceInterval;
        partial void OnCalendarEventRecurrenceIntervalChanging(global::System.Nullable<int> value);
        partial void OnCalendarEventRecurrenceIntervalChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventRecurrenceMaxInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> CalendarEventRecurrenceMaxInstances
        {
            get
            {
                return this._CalendarEventRecurrenceMaxInstances;
            }
            set
            {
                this.OnCalendarEventRecurrenceMaxInstancesChanging(value);
                this._CalendarEventRecurrenceMaxInstances = value;
                this.OnCalendarEventRecurrenceMaxInstancesChanged();
                this.OnPropertyChanged("CalendarEventRecurrenceMaxInstances");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _CalendarEventRecurrenceMaxInstances;
        partial void OnCalendarEventRecurrenceMaxInstancesChanging(global::System.Nullable<int> value);
        partial void OnCalendarEventRecurrenceMaxInstancesChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventRecurrenceEndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> CalendarEventRecurrenceEndDate
        {
            get
            {
                return this._CalendarEventRecurrenceEndDate;
            }
            set
            {
                this.OnCalendarEventRecurrenceEndDateChanging(value);
                this._CalendarEventRecurrenceEndDate = value;
                this.OnCalendarEventRecurrenceEndDateChanged();
                this.OnPropertyChanged("CalendarEventRecurrenceEndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _CalendarEventRecurrenceEndDate;
        partial void OnCalendarEventRecurrenceEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCalendarEventRecurrenceEndDateChanged();
        /// <summary>
        /// There are no comments for Property WeeklyCalendarEventRecurrenceDays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WeeklyCalendarEventRecurrenceDays
        {
            get
            {
                return this._WeeklyCalendarEventRecurrenceDays;
            }
            set
            {
                this.OnWeeklyCalendarEventRecurrenceDaysChanging(value);
                this._WeeklyCalendarEventRecurrenceDays = value;
                this.OnWeeklyCalendarEventRecurrenceDaysChanged();
                this.OnPropertyChanged("WeeklyCalendarEventRecurrenceDays");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WeeklyCalendarEventRecurrenceDays;
        partial void OnWeeklyCalendarEventRecurrenceDaysChanging(string value);
        partial void OnWeeklyCalendarEventRecurrenceDaysChanged();
        /// <summary>
        /// There are no comments for Property MonthlyCalendarEventRecurrenceTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> MonthlyCalendarEventRecurrenceTypeID
        {
            get
            {
                return this._MonthlyCalendarEventRecurrenceTypeID;
            }
            set
            {
                this.OnMonthlyCalendarEventRecurrenceTypeIDChanging(value);
                this._MonthlyCalendarEventRecurrenceTypeID = value;
                this.OnMonthlyCalendarEventRecurrenceTypeIDChanged();
                this.OnPropertyChanged("MonthlyCalendarEventRecurrenceTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _MonthlyCalendarEventRecurrenceTypeID;
        partial void OnMonthlyCalendarEventRecurrenceTypeIDChanging(global::System.Nullable<int> value);
        partial void OnMonthlyCalendarEventRecurrenceTypeIDChanged();
        /// <summary>
        /// There are no comments for Calendar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Calendar Calendar
        {
            get
            {
                return this._Calendar;
            }
            set
            {
                this._Calendar = value;
                this.OnPropertyChanged("Calendar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Calendar _Calendar;
        /// <summary>
        /// There are no comments for CalendarEventPrivacyType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CalendarEventPrivacyType CalendarEventPrivacyType
        {
            get
            {
                return this._CalendarEventPrivacyType;
            }
            set
            {
                this._CalendarEventPrivacyType = value;
                this.OnPropertyChanged("CalendarEventPrivacyType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CalendarEventPrivacyType _CalendarEventPrivacyType;
        /// <summary>
        /// There are no comments for CalendarEventStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CalendarEventStatus CalendarEventStatus
        {
            get
            {
                return this._CalendarEventStatus;
            }
            set
            {
                this._CalendarEventStatus = value;
                this.OnPropertyChanged("CalendarEventStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CalendarEventStatus _CalendarEventStatus;
        /// <summary>
        /// There are no comments for CalendarEventType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CalendarEventType CalendarEventType
        {
            get
            {
                return this._CalendarEventType;
            }
            set
            {
                this._CalendarEventType = value;
                this.OnPropertyChanged("CalendarEventType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CalendarEventType _CalendarEventType;
        /// <summary>
        /// There are no comments for MonthlyCalendarEventRecurrenceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MonthlyCalendarEventRecurrenceType MonthlyCalendarEventRecurrenceType
        {
            get
            {
                return this._MonthlyCalendarEventRecurrenceType;
            }
            set
            {
                this._MonthlyCalendarEventRecurrenceType = value;
                this.OnPropertyChanged("MonthlyCalendarEventRecurrenceType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MonthlyCalendarEventRecurrenceType _MonthlyCalendarEventRecurrenceType;
        /// <summary>
        /// There are no comments for CalendarEventRecurrenceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CalendarEventRecurrenceType CalendarEventRecurrenceType
        {
            get
            {
                return this._CalendarEventRecurrenceType;
            }
            set
            {
                this._CalendarEventRecurrenceType = value;
                this.OnPropertyChanged("CalendarEventRecurrenceType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CalendarEventRecurrenceType _CalendarEventRecurrenceType;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.CalendarEventPrivacyType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CalendarEventPrivacyTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CalendarEventPrivacyTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CalendarEventPrivacyTypeID")]
    public partial class CalendarEventPrivacyType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CalendarEventPrivacyType object.
        /// </summary>
        /// <param name="calendarEventPrivacyTypeID">Initial value of CalendarEventPrivacyTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CalendarEventPrivacyType CreateCalendarEventPrivacyType(int calendarEventPrivacyTypeID)
        {
            CalendarEventPrivacyType calendarEventPrivacyType = new CalendarEventPrivacyType();
            calendarEventPrivacyType.CalendarEventPrivacyTypeID = calendarEventPrivacyTypeID;
            return calendarEventPrivacyType;
        }
        /// <summary>
        /// There are no comments for Property CalendarEventPrivacyTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarEventPrivacyTypeID
        {
            get
            {
                return this._CalendarEventPrivacyTypeID;
            }
            set
            {
                this.OnCalendarEventPrivacyTypeIDChanging(value);
                this._CalendarEventPrivacyTypeID = value;
                this.OnCalendarEventPrivacyTypeIDChanged();
                this.OnPropertyChanged("CalendarEventPrivacyTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarEventPrivacyTypeID;
        partial void OnCalendarEventPrivacyTypeIDChanging(int value);
        partial void OnCalendarEventPrivacyTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventPrivacyTypeDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CalendarEventPrivacyTypeDescription
        {
            get
            {
                return this._CalendarEventPrivacyTypeDescription;
            }
            set
            {
                this.OnCalendarEventPrivacyTypeDescriptionChanging(value);
                this._CalendarEventPrivacyTypeDescription = value;
                this.OnCalendarEventPrivacyTypeDescriptionChanged();
                this.OnPropertyChanged("CalendarEventPrivacyTypeDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CalendarEventPrivacyTypeDescription;
        partial void OnCalendarEventPrivacyTypeDescriptionChanging(string value);
        partial void OnCalendarEventPrivacyTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> CalendarEvents
        {
            get
            {
                return this._CalendarEvents;
            }
            set
            {
                this._CalendarEvents = value;
                this.OnPropertyChanged("CalendarEvents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> _CalendarEvents = new global::System.Data.Services.Client.DataServiceCollection<CalendarEvent>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.CalendarEventStatus in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CalendarEventStatusID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CalendarEventStatuses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CalendarEventStatusID")]
    public partial class CalendarEventStatus : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CalendarEventStatus object.
        /// </summary>
        /// <param name="calendarEventStatusID">Initial value of CalendarEventStatusID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CalendarEventStatus CreateCalendarEventStatus(int calendarEventStatusID)
        {
            CalendarEventStatus calendarEventStatus = new CalendarEventStatus();
            calendarEventStatus.CalendarEventStatusID = calendarEventStatusID;
            return calendarEventStatus;
        }
        /// <summary>
        /// There are no comments for Property CalendarEventStatusID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarEventStatusID
        {
            get
            {
                return this._CalendarEventStatusID;
            }
            set
            {
                this.OnCalendarEventStatusIDChanging(value);
                this._CalendarEventStatusID = value;
                this.OnCalendarEventStatusIDChanged();
                this.OnPropertyChanged("CalendarEventStatusID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarEventStatusID;
        partial void OnCalendarEventStatusIDChanging(int value);
        partial void OnCalendarEventStatusIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventStatusDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CalendarEventStatusDescription
        {
            get
            {
                return this._CalendarEventStatusDescription;
            }
            set
            {
                this.OnCalendarEventStatusDescriptionChanging(value);
                this._CalendarEventStatusDescription = value;
                this.OnCalendarEventStatusDescriptionChanged();
                this.OnPropertyChanged("CalendarEventStatusDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CalendarEventStatusDescription;
        partial void OnCalendarEventStatusDescriptionChanging(string value);
        partial void OnCalendarEventStatusDescriptionChanged();
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> CalendarEvents
        {
            get
            {
                return this._CalendarEvents;
            }
            set
            {
                this._CalendarEvents = value;
                this.OnPropertyChanged("CalendarEvents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> _CalendarEvents = new global::System.Data.Services.Client.DataServiceCollection<CalendarEvent>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.CalendarEventType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CalendarEventTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CalendarEventTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CalendarEventTypeID")]
    public partial class CalendarEventType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CalendarEventType object.
        /// </summary>
        /// <param name="calendarEventTypeID">Initial value of CalendarEventTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CalendarEventType CreateCalendarEventType(int calendarEventTypeID)
        {
            CalendarEventType calendarEventType = new CalendarEventType();
            calendarEventType.CalendarEventTypeID = calendarEventTypeID;
            return calendarEventType;
        }
        /// <summary>
        /// There are no comments for Property CalendarEventTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarEventTypeID
        {
            get
            {
                return this._CalendarEventTypeID;
            }
            set
            {
                this.OnCalendarEventTypeIDChanging(value);
                this._CalendarEventTypeID = value;
                this.OnCalendarEventTypeIDChanged();
                this.OnPropertyChanged("CalendarEventTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarEventTypeID;
        partial void OnCalendarEventTypeIDChanging(int value);
        partial void OnCalendarEventTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventTypeDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CalendarEventTypeDescription
        {
            get
            {
                return this._CalendarEventTypeDescription;
            }
            set
            {
                this.OnCalendarEventTypeDescriptionChanging(value);
                this._CalendarEventTypeDescription = value;
                this.OnCalendarEventTypeDescriptionChanged();
                this.OnPropertyChanged("CalendarEventTypeDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CalendarEventTypeDescription;
        partial void OnCalendarEventTypeDescriptionChanging(string value);
        partial void OnCalendarEventTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
                this.OnPropertyChanged("Color");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Color;
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> CalendarEvents
        {
            get
            {
                return this._CalendarEvents;
            }
            set
            {
                this._CalendarEvents = value;
                this.OnPropertyChanged("CalendarEvents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> _CalendarEvents = new global::System.Data.Services.Client.DataServiceCollection<CalendarEvent>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.MonthlyCalendarEventRecurrenceType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MonthlyCalendarEventRecurrenceTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MonthlyCalendarEventRecurrenceTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MonthlyCalendarEventRecurrenceTypeID")]
    public partial class MonthlyCalendarEventRecurrenceType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MonthlyCalendarEventRecurrenceType object.
        /// </summary>
        /// <param name="monthlyCalendarEventRecurrenceTypeID">Initial value of MonthlyCalendarEventRecurrenceTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MonthlyCalendarEventRecurrenceType CreateMonthlyCalendarEventRecurrenceType(int monthlyCalendarEventRecurrenceTypeID)
        {
            MonthlyCalendarEventRecurrenceType monthlyCalendarEventRecurrenceType = new MonthlyCalendarEventRecurrenceType();
            monthlyCalendarEventRecurrenceType.MonthlyCalendarEventRecurrenceTypeID = monthlyCalendarEventRecurrenceTypeID;
            return monthlyCalendarEventRecurrenceType;
        }
        /// <summary>
        /// There are no comments for Property MonthlyCalendarEventRecurrenceTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int MonthlyCalendarEventRecurrenceTypeID
        {
            get
            {
                return this._MonthlyCalendarEventRecurrenceTypeID;
            }
            set
            {
                this.OnMonthlyCalendarEventRecurrenceTypeIDChanging(value);
                this._MonthlyCalendarEventRecurrenceTypeID = value;
                this.OnMonthlyCalendarEventRecurrenceTypeIDChanged();
                this.OnPropertyChanged("MonthlyCalendarEventRecurrenceTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _MonthlyCalendarEventRecurrenceTypeID;
        partial void OnMonthlyCalendarEventRecurrenceTypeIDChanging(int value);
        partial void OnMonthlyCalendarEventRecurrenceTypeIDChanged();
        /// <summary>
        /// There are no comments for Property MonthlyCalendarEventRecurrenceTypeDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MonthlyCalendarEventRecurrenceTypeDescription
        {
            get
            {
                return this._MonthlyCalendarEventRecurrenceTypeDescription;
            }
            set
            {
                this.OnMonthlyCalendarEventRecurrenceTypeDescriptionChanging(value);
                this._MonthlyCalendarEventRecurrenceTypeDescription = value;
                this.OnMonthlyCalendarEventRecurrenceTypeDescriptionChanged();
                this.OnPropertyChanged("MonthlyCalendarEventRecurrenceTypeDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MonthlyCalendarEventRecurrenceTypeDescription;
        partial void OnMonthlyCalendarEventRecurrenceTypeDescriptionChanging(string value);
        partial void OnMonthlyCalendarEventRecurrenceTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> CalendarEvents
        {
            get
            {
                return this._CalendarEvents;
            }
            set
            {
                this._CalendarEvents = value;
                this.OnPropertyChanged("CalendarEvents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> _CalendarEvents = new global::System.Data.Services.Client.DataServiceCollection<CalendarEvent>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.CalendarEventRecurrenceType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CalendarEventRecurrenceTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CalendarEventRecurrenceTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CalendarEventRecurrenceTypeID")]
    public partial class CalendarEventRecurrenceType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CalendarEventRecurrenceType object.
        /// </summary>
        /// <param name="calendarEventRecurrenceTypeID">Initial value of CalendarEventRecurrenceTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CalendarEventRecurrenceType CreateCalendarEventRecurrenceType(int calendarEventRecurrenceTypeID)
        {
            CalendarEventRecurrenceType calendarEventRecurrenceType = new CalendarEventRecurrenceType();
            calendarEventRecurrenceType.CalendarEventRecurrenceTypeID = calendarEventRecurrenceTypeID;
            return calendarEventRecurrenceType;
        }
        /// <summary>
        /// There are no comments for Property CalendarEventRecurrenceTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CalendarEventRecurrenceTypeID
        {
            get
            {
                return this._CalendarEventRecurrenceTypeID;
            }
            set
            {
                this.OnCalendarEventRecurrenceTypeIDChanging(value);
                this._CalendarEventRecurrenceTypeID = value;
                this.OnCalendarEventRecurrenceTypeIDChanged();
                this.OnPropertyChanged("CalendarEventRecurrenceTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CalendarEventRecurrenceTypeID;
        partial void OnCalendarEventRecurrenceTypeIDChanging(int value);
        partial void OnCalendarEventRecurrenceTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarEventRecurrenceTypeDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CalendarEventRecurrenceTypeDescription
        {
            get
            {
                return this._CalendarEventRecurrenceTypeDescription;
            }
            set
            {
                this.OnCalendarEventRecurrenceTypeDescriptionChanging(value);
                this._CalendarEventRecurrenceTypeDescription = value;
                this.OnCalendarEventRecurrenceTypeDescriptionChanged();
                this.OnPropertyChanged("CalendarEventRecurrenceTypeDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CalendarEventRecurrenceTypeDescription;
        partial void OnCalendarEventRecurrenceTypeDescriptionChanging(string value);
        partial void OnCalendarEventRecurrenceTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for CalendarEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> CalendarEvents
        {
            get
            {
                return this._CalendarEvents;
            }
            set
            {
                this._CalendarEvents = value;
                this.OnPropertyChanged("CalendarEvents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CalendarEvent> _CalendarEvents = new global::System.Data.Services.Client.DataServiceCollection<CalendarEvent>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CodeFirstNamespace.CalendarSubscription in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// CalendarID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CalendarSubscriptions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerID", "CalendarID")]
    public partial class CalendarSubscription : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CalendarSubscription object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="calendarID">Initial value of CalendarID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CalendarSubscription CreateCalendarSubscription(int customerID, global::System.Guid calendarID)
        {
            CalendarSubscription calendarSubscription = new CalendarSubscription();
            calendarSubscription.CustomerID = customerID;
            calendarSubscription.CalendarID = calendarID;
            return calendarSubscription;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
                this.OnPropertyChanged("CustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CalendarID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid CalendarID
        {
            get
            {
                return this._CalendarID;
            }
            set
            {
                this.OnCalendarIDChanging(value);
                this._CalendarID = value;
                this.OnCalendarIDChanged();
                this.OnPropertyChanged("CalendarID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _CalendarID;
        partial void OnCalendarIDChanging(global::System.Guid value);
        partial void OnCalendarIDChanged();
        /// <summary>
        /// There are no comments for Calendar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Calendar Calendar
        {
            get
            {
                return this._Calendar;
            }
            set
            {
                this._Calendar = value;
                this.OnPropertyChanged("Calendar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Calendar _Calendar;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
